HackerAlgorithm/Algorithm-Study

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(A) 경로당펑크 2077/sample.txt
Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(B) 너의 평점은/sample.txt
Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(D) 새벽의 탐정 게임/sample.txt
Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(F) 정사각형 세기/sample.txt
Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(G) 조각 케이크/sample.txt
Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(H) 크림 파스타/sample.txt
Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(I) 타이핑/sample.txt

add folder structure

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(A) 경로당펑크 2077/25205_seongju.cpp

[BOJ 25205] 경로당펑크 2077
none
마지막 문자 판단
none

seongju/[BOJ 25205] 경로당펑크 2077

---

Codeforces/(2022.05.23) ECR_129/(A) Game with Cards/seongju_ECR129_A.cpp

이성주 / [CodeForce ECR129] A

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(A) 경로당펑크 2077/seongju_25205.cpp

[BOJ 25205] 경로당 펑크 2077
.
마지막 문자 확인
.

이성주 / [BOJ 25205] 경로당펑크 2077

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(B) 너의 평점은/seongju_25206.cpp

이성주 / [BOJ 25206] 너의 평점은

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(D) 새벽의 탐정 게임/seongju_25208.cpp

[BOJ 25208] 새벽의 탐정 게임
최소이동횟수를 구하므로 bfs 사용
뚫려있는 방향을 포함한 3차원 visited 사용
도착한 칸이 'R'이면서 뚫려있는 면이 바닥이 아닌 경우, 해당 node를 queue에 추가하지 않음
bfs

이성주 / [BOJ 25208] 새벽의 탐정 게임

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(F) 정사각형 세기/seongju_25210.cpp

[BOJ 25210] 정사각형 세기
최소크기 정사각형과 최대크기 정사각형을 구함
특정 길이 `len`을 기준으로, 상하좌우 이동범위를 구함
구한 이동범위를 바탕으로 가능한 정사각형의 개수를 구함
.

이성주 / [BOJ 25210] 정사각형 세기

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(G) 조각 케이크/seongju_25212.cpp

[BOJ 25212] 조각 케이크
$N\leq 10$이므로 $2^{10}=1024$여서 브루트포스 실행
bitmasking으로 `1`부터 `(1<<N)-1`까지 전체탐색
```cpp
if (i & (1 << j)) // i의 j번째 비트가 켜져있으면 true return, 아니면 false return
```
브루트포스
비트마스킹

이성주 / [BOJ 25212] 조각 케이크

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(H) 크림 파스타/seongju_25214.cpp

[BOJ 25214] 크림 파스타
이전까지의 결과가 현재 상태에 영향을 주기 때문에 dp 사용
```cpp
// mini: 이전 index까지의 A[i] 최솟값
dp[i] = max(dp[i - 1], A[i] - mini);
```
다이나믹 프로그래밍

이성주 / [BOJ 25214] 크림 파스타

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(I) 타이핑/seongju_25215.cpp

[BOJ 25215] 타이핑
이전까지의 상태가 현재 상태를 결정하므로 dp 사용
$dp[i][0]$ $\rightarrow$ 현재 index $i$에서 마름모가 비활성화 상태인 경우, 버튼을 누른 최소 횟수
$dp[i][1]$ $\rightarrow$ 현재 index $i$에서 마름모가 활성화 상태인 경우, 버튼을 누른 최소 횟수
이전에 마름모가 비활성화 상태였는지(`dp[i-1][0]`) 활성화 상태였는지(`dp[i-1][1]`), 현재 index $i$의 문자가 소문자인지 대문자인지에 따라서 dp 값이 결정됨
다이나믹 프로그래밍

이성주 / [BOJ 25215] 타이핑

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(E) 샤카샤카/seongju_25209.cpp

[BOJ 25209] 샤카샤카
.
`Make_Index` - 3*3 배열이 무슨 블록인지 확인하여 Map에 저장
`Check_Rec1` - 대각선으로 이루어진 사각형 체크
`Check_Rec2` - 행과 열로 이루어진 사각형 체크
`Check_Number` - 숫자만큼 주변에 삼각형이 있는지 체크
`Find_Boundary1,2` - 사각형의 외부 경계선 탐색
`is_Empty1,2` - 사각형 내부가 전부 0인지 확인
.

이성주 / [BOJ 25209] 샤카샤카

---

Baekjoon Contest/(2022.06.04) 2022 서강대학교 청정수컵-새내기 Round/(A) 두~~부 두부 두부/seongju_25175.cpp

이성주 / [BOJ 25175] 두~~부 두부 두부

---

Baekjoon Contest/(2022.06.04) 2022 서강대학교 청정수컵-새내기 Round/(B) 청정수열 (Easy)/seongju_25176.cpp

이성주 / [BOJ 25176] 청정수열 (Easy)

---

Baekjoon Contest/(2022.06.04) 2022 서강대학교 청정수컵-새내기 Round/(C) 서강의 역사를 찾아서/seongju_25177.cpp

이성주 / [BOJ 25177] 서강의 역사를 찾아서

---

Baekjoon Contest/(2022.06.04) 2022 서강대학교 청정수컵-새내기 Round/(D) 두라무리 휴지/seongju_25178.cpp

이성주 / [BOJ 25178] 두라무리 휴지

---

Baekjoon Contest/(2022.06.04) 2022 서강대학교 청정수컵-새내기 Round/(E) 배스킨라빈스~N~귀엽고~깜찍하게~/seongju_25179.cpp

이성주 / [BOJ 25179] 배스킨라빈스~N~귀엽고~깜찍하게~

---

Baekjoon Contest/(2022.06.04) 2022 서강대학교 청정수컵-새내기 Round/(F) 썸 팰린드롬/seongju_25180.cpp

이성주 / [BOJ 25180] 썸 팰린드롬

---

Baekjoon Contest/(2022.06.04) 2022 서강대학교 청정수컵-새내기 Round/(G) Swap the elements/seongju_25181.cpp

이성주 / [BOJ 25181] Swap the elements

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(A) 경로당펑크 2077/dahee_A.cpp

김다희 / [BOJ 25206] 너의 평점은

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(B) 너의 평점은/INHA_B.cpp

김다희 / [BOJ 25205] 경로당펑크 2077

---

Baekjoon Contest/(2022.05.22) 2022 인하대학교 프로그래밍 경진대회(IUPC) Open Contest/(F) 정사각형 세기/INHA_F.cpp

김다희 / [BOJ 25210] 정사각형 세기 

---

Baekjoon Contest/(2022.06.06) 가희와 함께 하는 코딩테스트 4회/(B) 가희와 카오스 파풀라투스/seongju_25239.cpp

이성주 / [BOJ 25239] 가희와 카오스 파풀라투스 (B)

---

Baekjoon Contest/(2022.06.06) 가희와 함께 하는 코딩테스트 4회/(A) 가희와 방어율 무시/seongju_25238.cpp

이성주 / [BOJ 25238] 가희와 방어율 무시 (A)

---

Baekjoon Contest/(2022.06.06) 가희와 함께 하는 코딩테스트 4회/(C) 가희와 파일 탐색기 2/seongju_25240.cpp

이성주 / [BOJ 25240] 가희와 파일 탐색기 2 (C)

---

Baekjoon Contest/(2022.06.10) 제6회 천하제일 코딩대회 예선/(A) 심준의 병역판정검사/seongju_25285.cpp

이성주 / [BOJ 25285]  심준의 병역판정검사 (A)

---

Baekjoon Contest/(2022.06.10) 제6회 천하제일 코딩대회 예선/(B) 11월 11일/seongju_25286.cpp

이성주 / [BOJ 25286] 11월 11일 (B)

---

Baekjoon Contest/(2022.06.10) 제6회 천하제일 코딩대회 예선/(C) 순열 정렬/seongju_25287.cpp

이성주 / [BOJ 25287] 순열 정렬 (C)

---

Baekjoon Contest/(2022.07.02) UCPC 2022 예선/(PA) UCPC에서 가장 쉬운 문제 번호는/seongju_25311.cpp

이성주 / [BOJ 25311] UCPC 2022 예선 (PA)

---

Baekjoon Contest/(2022.07.02) UCPC 2022 예선/(PB) 200% Mixed Juice!/seongju_25312.cpp

이성주 / [BOJ 25312] UCPC 2022 예선 (PB)

---

Baekjoon Contest/(2022.07.02) UCPC 2022 예선/(A) 코딩은 체육과목 입니다/seongju_25314.cpp

이성주 / [BOJ 25314] UCPC 2022 예선 (A)

---

Baekjoon Contest/(2022.07.02) UCPC 2022 예선/(B) N수매화검법/seongju_25315.cpp

이성주 / [BOJ 25315] UCPC 2022 예선 (B)

---

Baekjoon Contest/(2022.07.02) UCPC 2022 예선/(E) solved.ac 2022/seongju_25318.cpp

이성주 / [BOJ 25318] UCPC 2022 예선 (E)

---

Baekjoon Contest/(2022.07.02) UCPC 2022 예선/(F) Twitch Plays VIIIbit Explorer/seongju_25319.cpp

이성주 / [BOJ 25319] UCPC 2022 예선 (F)

---

Baekjoon Contest/(2022.07.02) UCPC 2022 예선/(J) 수 정렬하기, 근데 이제 제곱수를 곁들인/seongju_25323.cpp

이성주 / [BOJ 25323] UCPC 2022 예선 (J)

---

Baekjoon Contest/(2022.07.08) 제6회 천하제일 코딩대회 본선/(A) Gravity Hackenbush/seongju_25335.cpp

이성주 / [BOJ 25335] 제6회 천하제일 코딩대회 본선 (A)

---

Baekjoon Contest/(2022.07.08) 제6회 천하제일 코딩대회 본선/(D) 바지 구매/seongju_25338.cpp

이성주 / [BOJ 25338] 제6회 천하제일 코딩대회 본선 (D)

---

Baekjoon Contest/(2022.07.08) 제6회 천하제일 코딩대회 본선/(E) 반전 수와 쿼리/seongju_25339.cpp

이성주 / [BOJ 25339] 제6회 천하제일 코딩대회 본선 (E)

---

Baekjoon Contest/(2022.07.08) 제6회 천하제일 코딩대회 본선/(F) 시간딱딱충/seongju_25340.cpp

이성주 / [BOJ 25340] 제6회 천하제일 코딩대회 본선 (F)

---

Baekjoon Contest/(2022.07.08) 제6회 천하제일 코딩대회 본선/(G) 인공 신경망/seongju_25341.cpp

이성주 / [BOJ 25341] 제6회 천하제일 코딩대회 본선 (G)

---

Baekjoon Contest/(2022.07.08) 제6회 천하제일 코딩대회 본선/(H) 최대 최소공배수/seongju_25342.cpp

이성주 / [BOJ 25342] 제6회 천하제일 코딩대회 본선 (H)

---

Baekjoon Contest/(2022.07.08) 제6회 천하제일 코딩대회 본선/(I) 최장 최장 증가 부분 수열/seongju_25343.cpp

이성주 / [BOJ 25343] 제6회 천하제일 코딩대회 본선 (I)
